"""descrição_da_migration

Revision ID: a2e266df4492
Revises: 
Create Date: 2025-05-14 10:47:16.633731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e266df4492'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_nome'), 'clientes', ['nome'], unique=False)
    op.create_index(op.f('ix_clientes_telefone'), 'clientes', ['telefone'], unique=True)
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('disponivel', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_categoria'), 'produtos', ['categoria'], unique=False)
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)
    op.create_index(op.f('ix_produtos_nome'), 'produtos', ['nome'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('mesas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('numero_identificador', sa.String(), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DISPONIVEL', 'OCUPADA', 'RESERVADA', 'FECHADA', name='statusmesa'), nullable=False),
    sa.Column('qr_code_hash', sa.String(), nullable=True),
    sa.Column('id_cliente_associado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente_associado'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mesas_id'), 'mesas', ['id'], unique=False)
    op.create_index(op.f('ix_mesas_numero_identificador'), 'mesas', ['numero_identificador'], unique=True)
    op.create_index(op.f('ix_mesas_qr_code_hash'), 'mesas', ['qr_code_hash'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('comandas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_mesa', sa.String(), nullable=False),
    sa.Column('id_cliente_associado', sa.String(), nullable=True),
    sa.Column('status_comanda', sa.Enum('ABERTA', 'FECHADA', 'PAGA_PARCIALMENTE', 'PAGA_TOTALMENTE', 'CANCELADA', 'EM_FIADO', name='statuscomanda'), nullable=False),
    sa.Column('valor_total_calculado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_fiado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente_associado'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_mesa'], ['mesas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comandas_id'), 'comandas', ['id'], unique=False)
    op.create_table('itens_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_comanda', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_comanda'], ['comandas.id'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_pedido_id'), 'itens_pedido', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_pedido_id'), table_name='itens_pedido')
    op.drop_table('itens_pedido')
    op.drop_index(op.f('ix_comandas_id'), table_name='comandas')
    op.drop_table('comandas')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_mesas_qr_code_hash'), table_name='mesas')
    op.drop_index(op.f('ix_mesas_numero_identificador'), table_name='mesas')
    op.drop_index(op.f('ix_mesas_id'), table_name='mesas')
    op.drop_table('mesas')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_produtos_nome'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_categoria'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_clientes_telefone'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_nome'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
