"""Criação das tabelas iniciais

Revision ID: f9b7c3f8bc38
Revises: cba1cf48d1e7
Create Date: 2025-05-21 11:04:35.892226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9b7c3f8bc38'
down_revision: Union[str, None] = 'cba1cf48d1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fiados', sa.Column('data_registro', sa.DateTime(), nullable=True))
    op.drop_column('fiados', 'created_at')
    op.add_column('pagamentos', sa.Column('data_pagamento', sa.DateTime(), nullable=True))
    op.drop_column('pagamentos', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagamentos', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('pagamentos', 'data_pagamento')
    op.add_column('fiados', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('fiados', 'data_registro')
    # ### end Alembic commands ###
